spring:
  application:
    name: Config-Prod
eureka:
  client:
    fetch-registry: true
      register-with-eureka: true
        service-url:
          dafaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
